---
title: "qPCR"
author: "MNitschke"
date: "19/05/2020"
output: html_document
---

```{r}
library(tidyverse)
library(rstatix)
library(ggpubr)
library(patchwork)
```

# qPCR count data import

```{r}
data <- read_csv("qpcr_cells_cm3.csv") %>%
    mutate(Site = as.factor(Site),
         Habitat = fct_relevel(Habitat, "Water", "Sediment", "Macroalgae")) %>%
    unite(Habitat, Season, col = "Habitat_Season", sep = " ", remove = FALSE) %>%
    unite(Year, Season, Habitat, Site, Replicate, Genus, col = "Full_label", sep = "_", remove = FALSE) %>%
    mutate(Habitat_Season = fct_relevel(Habitat_Season, c("Water Spawning", "Water Summer", "Sediment Spawning", "Sediment Summer", "Macroalgae Spawning", "Macroalgae Summer")))
```

# Two-way ANOVA

```{r}
# Identify outliers
data_out <- data %>%
  group_by(Habitat, Season, Genus) %>%
  identify_outliers(Cells_cm3) %>%
  filter(is.extreme == TRUE)

# Remove outliers
data_no <- data %>%
  filter(!(Full_label %in% data_out$Full_label)) # Remove extreme outliers

# Summary statistics
data_ss <- data_no %>%
  group_by(Habitat, Genus) %>%
  get_summary_stats(Cells_cm3, type = "mean_sd")

data_ss <- data_no %>%
  group_by(Season, Genus) %>%
  get_summary_stats(Cells_cm3, type = "mean_sd")

data_ss <- data_no %>%
  group_by(Habitat, Season, Genus) %>%
  get_summary_stats(Cells_cm3, type = "mean_sd")

# Create a QQ plot of residuals - all points fall approximately along the line - normality was 
ggqqplot(data_no %>% filter(Genus == "Cladocopium"), "Cells_cm3", ggtheme = theme_bw()) +
  facet_grid(Habitat ~ Season)
ggqqplot(data_no %>% filter(Genus == "Durusdinium"), "Cells_cm3", ggtheme = theme_bw()) +
  facet_grid(Habitat ~ Season)
ggqqplot(data_no %>% filter(Genus == "Symbiodinium"), "Cells_cm3", ggtheme = theme_bw()) +
  facet_grid(Habitat ~ Season)

# Levenes test of Homogeneity - all tests fail
data_no %>%
  filter(Genus == "Cladocopium") %>% 
  levene_test(Cells_cm3 ~ Habitat * Season)

data_no %>%
  filter(Genus == "Durusdinium") %>% 
  levene_test(Cells_cm3 ~ Habitat * Season)

data_no %>%
  filter(Genus == "Symbiodinium") %>% 
  levene_test(Cells_cm3 ~ Habitat * Season)

# Try log-transforming - all tests still fail

data_no %>%
  filter(Genus == "Cladocopium") %>%
  mutate(log_Cells_cm3 = log(Cells_cm3)) %>%
  levene_test(log_Cells_cm3 ~ Habitat * Season)

data_no %>%
  filter(Genus == "Durusdinium") %>% 
  mutate(log_Cells_cm3 = log(Cells_cm3)) %>%
  levene_test(log_Cells_cm3 ~ Habitat * Season)

data_no %>%
  filter(Genus == "Symbiodinium") %>% 
  mutate(log_Cells_cm3 = log(Cells_cm3)) %>%
  levene_test(log_Cells_cm3 ~ Habitat * Season)

# There are no non-parametric equivalents to a two-way ANOVA. So instead, we will use a welch one way test (does not assume equal variances) for Habitat and Season, separately
```

## Habitat - Welch Anova test & Games Howell test

```{r}
res_welch_c <- data_no %>%
  filter(Genus == "Cladocopium") %>% 
  welch_anova_test(Cells_cm3 ~ Habitat) %>%
  mutate(genus = "Cladocopium")

res_welch_d <- data_no %>%
  filter(Genus == "Durusdinium") %>% 
  welch_anova_test(Cells_cm3 ~ Habitat) %>%
  mutate(genus = "Durusdinium")

res_welch_s <- data_no %>%
  filter(Genus == "Symbiodinium") %>% 
  welch_anova_test(Cells_cm3 ~ Habitat) %>%
  mutate(genus = "Symbiodinium")

welch_res_hab <- rbind(res_welch_c, res_welch_d, res_welch_s) %>%
  mutate(factor = "habitat")
write_csv(welch_res_hab, "welch_res_hab.csv")

res_welch_c_pwc <- data_no %>%
  filter(Genus == "Cladocopium") %>%
  games_howell_test(Cells_cm3 ~ Habitat) %>%
  mutate(genus = "Cladocopium")

res_welch_d_pwc <- data_no %>%
  filter(Genus == "Durusdinium") %>%
  games_howell_test(Cells_cm3 ~ Habitat) %>%
  mutate(genus = "Durusdinium")

res_welch_s_pwc <- data_no %>%
  filter(Genus == "Symbiodinium") %>%
  games_howell_test(Cells_cm3 ~ Habitat) %>%
  mutate(genus = "Symbiodinium")

gh_res_hab <- rbind(res_welch_c_pwc, res_welch_d_pwc, res_welch_s_pwc)
write_csv(gh_res_hab, "gh_res_hab.csv")
```

## Season - Welch Anova test & Games Howell test

```{r}
res_welch_c_w <- data_no %>%
  filter(Genus == "Cladocopium") %>%
  filter(Habitat == "Water") %>%
  welch_anova_test(Cells_cm3 ~ Season) %>%
  mutate(genus = "Cladocopium_water")

res_welch_d_w <- data_no %>%
  filter(Genus == "Durusdinium") %>%
    filter(Habitat == "Water") %>%
  welch_anova_test(Cells_cm3 ~ Season) %>%
  mutate(genus = "Durusdinium_water")

res_welch_s_w <- data_no %>%
  filter(Genus == "Symbiodinium") %>%
    filter(Habitat == "Water") %>%
  welch_anova_test(Cells_cm3 ~ Season) %>%
  mutate(genus = "Symbiodinium_water")

# res_welch_c <- data_no %>%
#   filter(Genus == "Cladocopium") %>%
#   filter(Habitat == "Sediment") %>%
#   welch_anova_test(Cells_cm3 ~ Season) %>%
#   mutate(genus = "Cladocopium")

# res_welch_d <- data_no %>%
#   filter(Genus == "Durusdinium") %>%
#     filter(Habitat == "Sediment") %>%
#   welch_anova_test(Cells_cm3 ~ Season) %>%
#   mutate(genus = "Durusdinium")

res_welch_s_s <- data_no %>%
  filter(Genus == "Symbiodinium") %>%
    filter(Habitat == "Sediment") %>%
  welch_anova_test(Cells_cm3 ~ Season) %>%
  mutate(genus = "Symbiodinium_sediment")

res_welch_c_m <- data_no %>%
  filter(Genus == "Cladocopium") %>%
  filter(Habitat == "Macroalgae") %>%
  welch_anova_test(Cells_cm3 ~ Season) %>%
  mutate(genus = "Cladocopium_macroalgae")

res_welch_d_m <- data_no %>%
  filter(Genus == "Durusdinium") %>%
    filter(Habitat == "Macroalgae") %>%
  welch_anova_test(Cells_cm3 ~ Season) %>%
  mutate(genus = "Durusdinium__macroalgae")

res_welch_s_m <- data_no %>%
  filter(Genus == "Symbiodinium") %>%
    filter(Habitat == "Macroalgae") %>%
  welch_anova_test(Cells_cm3 ~ Season) %>%
  mutate(genus = "Symbiodinium__macroalgae")

welch_res_seas <- rbind(res_welch_c_w, res_welch_d_w, res_welch_s_w, res_welch_s_s, res_welch_c_m, res_welch_d_m, res_welch_s_m)
write_csv(welch_res_seas, "welch_res_seas.csv")
```

```{r}
res_welch_c_pwc <- data_no %>%
  filter(Genus == "Cladocopium") %>%
  games_howell_test(Cells_cm3 ~ Season) %>%
  mutate(genus = "Cladocopium")

res_welch_d_pwc <- data_no %>%
  filter(Genus == "Durusdinium") %>%
  games_howell_test(Cells_cm3 ~ Season) %>%
  mutate(genus = "Durusdinium")

res_welch_s_pwc <- data_no %>%
  filter(Genus == "Symbiodinium") %>%
  games_howell_test(Cells_cm3 ~ Season) %>%
  mutate(genus = "Symbiodinium")

gh_res_seas <- rbind(res_welch_c_pwc, res_welch_d_pwc, res_welch_s_pwc)
write_csv(gh_res_seas, "gh_res_seas.csv")
```

# Figure 5

```{r}
give.n <- function(x){
   return(c(y = mean(x), label = length(x)))
}

ggplot(data_no, aes(Habitat_Season, Cells_cm3, fill = Habitat_Season)) +
          geom_boxplot() +
          facet_wrap(~Genus, ncol = 1) +
          stat_summary(fun.data = give.n, geom = "text", position = position_nudge(y = 1)) +
          scale_shape_manual(values = c(21,22)) +
          scale_y_log10(breaks=c(.01,.1,1,10,100,1000)) +
          theme(aspect.ratio = 1) +
          theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5), legend.position = "none") +
          scale_fill_manual(values = c("#BCD6E9", "#1F77B4FF", "#FFD9B7", "#FF7F0EFF", "#C0E3C0", "#2CA02CFF"))
```